services:
  # Development service
  dev:
    build:
      context: .
      target: development        # Target the development stage from Dockerfile
    ports:
      - '3002:3002'              # Expose port 3002 for development
    volumes:
      - .:/app             # Bind mount local directory to container
      - node_modules:/app/node_modules         # Exclude local node_modules
    stdin_open: true
    tty: true
    restart: always
    environment:
      - WDS_SOCKET_HOST=0.0.0.0  # Ensure the dev server is accessible from outside the container
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    profiles:
      - develop

  # Production service
  prod:
    build:
      context: .
      target: production          # Target the production stage from Dockerfile
    ports:
      - '80:80'                   # Expose port 80 for production
    restart: always               # Restart if the container crashes

volumes:
  node_modules: